services:
  rest-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - "5286:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - Auth0_Audience=${Auth0_Audience}
      - Auth0_ClientId=${Auth0_ClientId}
      - Auth0_ClientSecret=${Auth0_ClientSecret}
      - Auth0_Domain=${Auth0_Domain}
      - REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING:-redis:6379}
    volumes:
        - ./rest:/src
        - rest-bin:/src/bin
        - rest-obj:/src/obj

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  rest-bin:
  rest-obj: