name: Service REST CI

on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - "services/rest/**"
  pull_request:
    branches:
      - main
    paths:
      - "services/rest/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: services/rest

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    
    env:
      Auth0_Audience: ${{ secrets.AUTH0_AUDIENCE }}
      Auth0_ClientId: ${{ secrets.AUTH0_CLIENT_ID }}
      Auth0_ClientSecret: ${{ secrets.AUTH0_CLIENT_SECRET }}
      Auth0_Authority: ${{ secrets.AUTH0_AUTHORITY }}
      Auth0_Domain: ${{ secrets.AUTH0_DOMAIN }}
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore NuGet packages
        run: dotnet restore rest/rest.csproj 

      - name: Build REST API
        run: dotnet build rest/rest.csproj -c Release --no-restore

      - name: Start API
        run: |
          export ConnectionStrings__DefaultConnection="Data Source=rest/movies.db"
          export REDIS_CONNECTION_STRING="127.0.0.1:6379"
          dotnet run --project rest/rest.csproj &
          sleep 15

      - name: Verify API is running
        run: curl http://localhost:5286

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests
        run: |
          newman run tests/REST-API-v1.postman_collection.json \
          -e tests/REST-API-v1.postman_environment.json \
          --env-var "baseUrl=http://localhost:5286" \
          --env-var "auth0_username=${{ secrets.AUTH0_USERNAME }}" \
          --env-var "auth0_password=${{ secrets.AUTH0_PASSWORD }}"

      - name: Print API logs
        if: failure()
        run: cat api.log
